name: ci-cd
on:
  push:
    branches: main
  pull_request:
    branches: main
jobs:
  lint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        name: Cache NPM Dependencies
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - name: Lint Website
        run: npx eslint --fix 'src/**/*.js'
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      name: Cache NPM Dependencies
      with:
        node-version: 24
        cache: 'npm'
        cache-dependency-path: package-lock.json
    - run: npm ci
    - name: Test Website
      run: npm test
  staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        name: Cache NPM Dependencies
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - name: Build site
        run: npm run build
      - name: Deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
  deploy:
    needs: [test, lint, staging]
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v5
        name: Cache NPM Dependencies
        with:
          node-version: 24
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - run: npm ci
      - name: Build site
        run: npm run build
      - name: Deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=dist --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
